# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Adam Boaler
description: >- # site description
  Full stack web developer from the UK. Open-source enthusiast, Python aficionado. See my projects <a href="https://github.com/adamb70" target="_blank" rel="noopener">on Github</a>.
lang: en-GB # default lang
timezone: Europe/London # set your timezone
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Adam Boaler
  bio: >- # tell to the world
    Full stack web developer from the UK. Open-source enthusiast, Python aficionado. See my projects <a href="https://github.com/adamb70" target="_blank" rel="noopener">on Github</a>.
  username: Adam Boaler # general username
  github: adamb70 # github username
  # twitter: username # twitter username
  # facebook: username # facebook username
  # email: your-email@email.com # email adress
  avatar: /assets/img/avatar.jpg

# URL settings
url: "https://boaler.uk"
baseurl:
permalink: /:title/
google_analytics: # leave blank if not using
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles

sass:
  style: compressed

include:
  - _redirects
  - .htaccess

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec
